# Generated by Django 2.2.7 on 2019-11-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamy',
            name='name',
            field=models.CharField(default='admin', max_length=16),
        ),
    ]
